---
title: "CHNS Covid-19 Dataset"
author: "Estya"
date: "July 27, 2020"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
## CHNS Covid-19 Dataset

1) Install packages
#relevant packages: "covid19.analytics", "tidycovid19", "nCov2019", "coronavirus", etc.
#selected package:"covid19.analytics
```{r set up}
#load library from 'covid19.analytics' and 'coronavirus' package
library(covid19.analytics)
library(coronavirus)
library(tidyverse)
library(lubridate)
```
2) Load library and whole dataset into R

Notes: ### - means still working on this
```{r load covid data}
#load whole dataset into R
covid19.data(case="ts-All")

#place dataset in object 'alldata' and check 'alldata' 
alldata<-(covid19.data(case="ts-All"))


#list dataset by selected countries and confirmed incidences within these selected countries
str(alldata)
head(alldata)

###working on this code right now - alldates<-alldata[which (alldata$Country.Region=='Brunei','Cambodia','China','Indonesia', 'Japan','Korea,South','Malaysia','Singapore','Taiwan','Vietnam','Laos','Burma','India', 'Philippines','Thailand'), c(2,6:194)]
###alldates
```
3) Calculate daily data to monthly data (insert mathematical function that will loop)
```{r aggregate covid data}
#aggregate monthly data from dailu data (to use loop function) for selected countries

df <- alldata %>%
  pivot_longer(names(.)[5: (ncol(.) - 1)], 
               names_to = 'date', values_to = 'cases') %>%
  select(-Long, -Lat, -Province.State) %>%
  mutate(date = ymd(date)) %>%
  mutate(month = month(date)) %>%
  group_by(Country.Region, month) %>%
  summarize(cases = max(cases)) %>%
  filter(between(month, 1, 8)) %>%
  rename(country = Country.Region)

df %>%
  write_csv('covid_cases.csv')
```


```{r merge data}
# change some of the country names in fire data 
# just to match that in covid data
df_fire <- read_csv('national_fire.csv') %>%
  mutate(country = str_replace(country, 'United States', 'US')) %>%
  mutate(country = str_replace(country, 'Korea', 'Korea, South')) 

# merge the two data files
# some countries are missing in fire data coz it's 0
df %>% 
  left_join(df_fire, by = c('country', 'month'))

```

